config/routes.rb
Rails.application.routes.draw do

  scope "org/:org_permalink", :as => 'organization' do
    resources :domains, :only => [:index, :new, :create, :destroy] do
      match :verify, :on => :member, :via => [:get, :post]
      get :setup, :on => :member
      post :check, :on => :member
    end
    resources :servers, :except => [:index] do
      resources :domains, :only => [:index, :new, :create, :destroy] do
        match :verify, :on => :member, :via => [:get, :post]
        get :setup, :on => :member
        post :check, :on => :member
      end
      resources :track_domains do
        post :toggle_ssl, :on => :member
        post :check, :on => :member
      end
      resources :credentials
      resources :routes
      resources :http_endpoints
      resources :smtp_endpoints
      resources :address_endpoints
      resources :ip_pool_rules
      resources :messages do
        get :incoming, :on => :collection
        get :outgoing, :on => :collection
        get :held, :on => :collection
        get :activity, :on => :member
        get :plain, :on => :member
        get :html, :on => :member
        get :html_raw, :on => :member
        get :attachments, :on => :member
        get :headers, :on => :member
        get :attachment, :on => :member
        get :download, :on => :member
        get :spam_checks, :on => :member
        post :retry, :on => :member
        post :cancel_hold, :on => :member
        get :suppressions, :on => :collection
        delete :remove_from_queue, :on => :member
        get :deliveries, :on => :member
      end
      resources :webhooks do
        get :history, :on => :collection
        get 'history/:uuid', :on => :collection, :action => 'history_request', :as => 'history_request'
      end
      get :limits, :on => :member
      get :retention, :on => :member
      get :queue, :on => :member
      get :spam, :on => :member
      get :delete, :on => :member
      get 'help/outgoing' => 'help#outgoing'
      get 'help/incoming' => 'help#incoming'
      get :advanced, :on => :member
      post :suspend, :on => :member
      post :unsuspend, :on => :member
    end
    resources :users do
      post :make_owner, :on => :member
    end
    resources :ip_pool_rules
    resources :ip_pools, :controller => 'organization_ip_pools' do
      put :assignments, :on => :collection
    end
    root 'servers#index'
    get 'settings' => 'organizations#edit'
    patch 'settings' => 'organizations#update'
    get 'delete' => 'organizations#delete'
    delete 'delete' => 'organizations#destroy'
  end

  resources :organizations, :except => [:index]
  resources :ip_pools do
    resources :ip_addresses
  end

  get 'settings' => 'user#edit'
  patch 'settings' => 'user#update'
  post 'persist' => 'sessions#persist'

  match 'verify' => 'user#verify', :via => [:get, :post]
  get 'signup/:invite_token' => 'user#new', :as => 'new_signup'
  post 'signup' => 'user#create'
  match 'join/:token' => 'user#join', :via => [:get, :post, :delete], :as => 'join'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'login/token' => 'sessions#create_with_token'
  delete 'logout' => 'sessions#destroy'
  match 'login/reset' => 'sessions#begin_password_reset', :via => [:get, :post]
  match 'login/reset/:token' => 'sessions#finish_password_reset', :via => [:get, :post]
  root 'organizations#index'
  get 'ip' => 'sessions#ip'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                               :integer          not null, primary key
#  uuid                             :string(255)
#  first_name                       :string(255)
#  last_name                        :string(255)
#  email_address                    :string(255)
#  password_digest                  :string(255)
#  time_zone                        :string(255)
#  email_verification_token         :string(255)
#  email_verified_at                :datetime
#  created_at                       :datetime
#  updated_at                       :datetime
#  password_reset_token             :string(255)
#  password_reset_token_valid_until :datetime
#  admin                            :boolean          default(FALSE)
#
# Indexes
#
#  index_users_on_email_address  (email_address)
#  index_users_on_uuid           (uuid)
#

class User < ApplicationRecord

  include HasUUID

  require_dependency 'user/authentication'

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email_address, :presence => true, :uniqueness => true, :format => {:with => /@/}
  validates :time_zone, :presence => true

  default_value :time_zone, -> { 'UTC' }

  has_many :organization_users, :dependent => :destroy, :as => :user
  has_many :organizations, :through => :organization_users

  scope :verified, -> { where.not(:email_verified_at => nil) }

  when_attribute :email_address, :changes_to => :anything do
    before_save do |was, now|
      unless self.new_record? && self.email_verified_at
        self.email_verification_token = rand(999999).to_s.rjust(6, '0')
        self.email_verified_at = nil
      end
    end

    after_commit do |was, new|
      if self.email_verified_at.nil? && was.present?
        AppMailer.verify_email_address(self).deliver
      end
    end
  end

  def organizations_scope
    @organizations_scope ||= begin
      if self.admin?
        Organization.present
      else
        self.organizations.present
      end
    end
  end

  def name
    "#{first_name} #{last_name}"
  end

  def to_param
    uuid
  end

  def verify!
    self.email_verified_at = Time.now
    self.save!
  end

  def verified?
    email_verified_at.present?
  end

  def md5_for_gravatar
    @md5_for_gravatar ||= Digest::MD5.hexdigest(email_address.to_s.downcase)
  end

  def avatar_url
    @avatar_url ||= email_address ? "https://secure.gravatar.com/avatar/#{md5_for_gravatar}?rating=PG&size=120&d=mm" : nil
  end

  def email_tag
    "#{name} <#{email_address}>"
  end

  def generate_login_token
    JWT.encode({'user' => self.id, 'timestamp' => Time.now.to_f}, Postal.signing_key.to_s, 'HS256')
  end

  def self.[](email)
    where(:email_address => email).first
  end

end

app/models/user/authentication.rb
class User

  has_secure_password

  validates :password, :length => {:minimum => 8, :allow_blank => true}

  when_attribute :password_digest, :changes_to => :anything do
    before_save do
      self.password_reset_token = nil
      self.password_reset_token_valid_until = nil
    end
  end

  def self.authenticate(email_address, password)
    user = where(:email_address => email_address).first
    raise Postal::Errors::AuthenticationError.new('InvalidEmailAddress') if user.nil?
    raise Postal::Errors::AuthenticationError.new('InvalidPassword') unless user.authenticate(password)
    user
  end

  def authenticate_with_previous_password_first(unencrypted_password)
    if password_digest_changed?
      BCrypt::Password.new(password_digest_was).is_password?(unencrypted_password) && self
    else
      authenticate(unencrypted_password)
    end
  end

  def begin_password_reset(return_to = nil)
    self.password_reset_token = Nifty::Utils::RandomString.generate(:length => 24)
    self.password_reset_token_valid_until = 1.day.from_now
    self.save!
    AppMailer.password_reset(self, return_to).deliver
  end

end

class Postal::Errors::AuthenticationError < Postal::Error

  attr_reader :error

  def initialize(error)
    @error = error
  end

  def to_s
    "Authentication Failed: #{@error}"
  end

end

# -*- SkipSchemaAnnotations

app/controllers/user_controller.rb
class UserController < ApplicationController

  skip_before_action :login_required, :only => [:new, :create, :join]
  skip_before_action :verified_email_required, :only => [:edit, :update, :verify]

  def new
    @user_invite = UserInvite.active.find_by!(:uuid => params[:invite_token])
    @user = User.new
    @user.email_address = @user_invite.email_address
    render :layout => 'sub'
  end

  def create
    @user_invite = UserInvite.active.find_by!(:uuid => params[:invite_token])
    @user = User.new(params.require(:user).permit(:first_name, :last_name, :email_address, :password, :password_confirmation))
    @user.email_verified_at = Time.now
    if @user.save
      @user_invite.accept(@user)
      self.current_user = @user
      redirect_to root_path
    else
      render 'new', :layout => 'sub'
    end
  end

  def join
    if @invite = UserInvite.where(:uuid => params[:token]).where("expires_at > ?", Time.now).first
      if logged_in?
        if request.post?
          @invite.accept(current_user)
          redirect_to_with_json root_path(:nrd => 1), :notice => "Invitation has been accepted successfully. You now have access to this organization."
        elsif request.delete?
          @invite.reject
          redirect_to_with_json root_path(:nrd => 1), :notice => "Invitation has been rejected successfully."
        else
          @organizations = @invite.organizations.order(:name).to_a
        end
      else
        redirect_to new_signup_path(params[:token])
      end
    else
      redirect_to_with_json root_path(:nrd => 1), :alert => "The invite URL you have has expired. Please ask the person who invited you to re-send your invitation."
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    @user.attributes = params.require(:user).permit(:first_name, :last_name, :time_zone, :email_address, :password, :password_confirmation)

    if @user.authenticate_with_previous_password_first(params[:password])
      @password_correct = true
    else
      respond_to do |wants|
        wants.html do
          flash.now[:alert] = "The current password you have entered is incorrect. Please check and try again."
          render 'edit'
        end
        wants.json do
          render :json => {:alert => "The current password you've entered is incorrect. Please check and try again"}
        end
      end
      return
    end

    email_changed = @user.email_address_changed?

    if @user.save
      if email_changed
        redirect_to_with_json verify_path(:return_to => settings_path), :notice => "Your settings have been updated successfully. As you've changed, your e-mail address you'll need to verify it before you can continue."
      else
        redirect_to_with_json settings_path, :notice => "Your settings have been updated successfully."
      end
    else
      render_form_errors 'edit', @user
    end
  end

  def verify
    if request.post?
      if params[:code].to_s.strip == current_user.email_verification_token.to_s || (Rails.env.development? && params[:code].to_s.strip == "123456")
        current_user.verify!
        redirect_to_with_json [:return_to, root_path], :notice => "Thanks - your e-mail address has been verified successfully."
      else
        flash_now :alert, "The code you've entered isn't correct. Please check and try again."
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include WithinOrganization
  before_action :require_organization_admin
  before_action :require_organization_owner, :only => [:make_owner]
  before_action { params[:id] && @user = params[:invite] ? organization.user_invites.find_by_uuid!(params[:id]) : organization.users.find_by_uuid!(params[:id]) }

  def index
    @users = organization.organization_users.where(:user_type => 'User').includes(:user).to_a.sort_by { |u| "#{u.user.first_name}#{u.user.last_name}".upcase }
    @pending_users = organization.organization_users.where(:user_type => "UserInvite").includes(:user).to_a.sort_by { |u| u.user.email_address.upcase }
  end

  def new
    @organization_user = organization.organization_users.build
  end

  def create
    @organization_user = organization.organization_users.build(params.require(:organization_user).permit(:email_address, :admin, :all_servers))
    if @organization_user.save
      AppMailer.user_invite(@organization_user.user, organization).deliver
      redirect_to_with_json [organization, :users], :notice => "An invitation will be sent to #{@organization_user.user.email_address} which will allow them to access your organization."
    else
      render_form_errors 'new', @organization_user
    end
  end

  def edit
    @organization_user = organization.user_assignment(@user)
  end

  def update
    @organization_user = organization.user_assignment(@user)
    if @organization_user.update(params.require(:organization_user).permit(:admin))
      redirect_to_with_json [organization, :users], :notice => "Permissions for #{@organization_user.user.name} have been updated successfully."
    else
      render_form_errors 'edit', @organization_user
    end
  end

  def destroy
    if @user == current_user
      redirect_to_with_json [organization, :users], :alert => "You cannot revoke your own access."
      return
    end

    if @user == organization.owner
      redirect_to_with_json [organization, :users], :alert => "You cannot revoke the organization owner's access."
      return
    end

    organization.organization_users.where(:user => @user).destroy_all
    redirect_to_with_json [organization, :users], :notice => "#{@user.name} has been removed from this organization"
  end

  def make_owner
    if @user.is_a?(User)
      organization.make_owner(@user)
      redirect_to_with_json [organization, :users], :notice => "#{@user.name} is now the owner of this organization."
    else
      raise Postal::Error, "User must be a User not a UserInvite to make owner"
    end
  end

end

app/views/user/edit.html.haml
- page_title << "My Settings"
.pageHeader
  %h1.pageHeader__title
    My Settings
.pageContent.pageContent--compact
  = form_for @user, :url => settings_path, :remote => true do |f|
    = f.error_messages
    %fieldset.fieldSet
      .fieldSet__field
        = label_tag :password, 'Your Password', :class => 'fieldSet__label'
        .fieldSet__input
          = password_field_tag :password, params[:password], :autofocus => @password_correct.nil?, :disabled => @password_correct, :class => 'input input--text', :placeholder => "Enter your current password to change your details"
          - if @password_correct
            = hidden_field_tag :password, params[:password]
          %p.fieldSet__text
            In order to protect your account, you need to enter your current password in the field above
            to authenticate the change of your details.

      .fieldSet__title
        Your details

      .fieldSet__field
        = f.label :first_name, "Name", :class => 'fieldSet__label'
        .fieldSet__input
          .inputPair
            = f.text_field :first_name, :class => 'input input--text', :autofocus => @password_correct
            = f.text_field :last_name, :class => 'input input--text'
      .fieldSet__field
        = f.label :email_address, :class => 'fieldSet__label'
        .fieldSet__input
          = f.text_field :email_address, :class => 'input input--text'
          %p.fieldSet__text
            If you change your e-mail address, you'll need to verify that you own the new one before
            you can continue using your account.

      .fieldSet__field
        = f.label :time_zone, :class => 'fieldSet__label'
        .fieldSet__input
          = f.time_zone_select :time_zone, [], {}, :class => 'input input--select'
          %p.fieldSet__text
            Choose the time zone that you'd like times to be displayed to you when you use our
            web interface. By default, times are displayed in UTC.

      .fieldSet__title
        Change your password?
      .fieldSet__field
        = f.label :password, "New Password", :class => 'fieldSet__label'
        .fieldSet__input
          .inputPair
            = f.password_field :password, :class => 'input input--text', :placeholder => "•••••••••••", :value => @user.password
            = f.password_field :password_confirmation, :class => 'input input--text', :placeholder => "and confirm it", :value => @user.password_confirmation


    %p.fieldSetSubmit.buttonSet
      = f.submit "Save Settings", :class => 'button button--positive js-form-submit'

app/views/user/join.html.haml
- page_title << "Join Organization"
.pageHeader
  %h1.pageHeader__title
    Join Organization
.pageContent.pageContent--compact
  %h2.pageContent__intro.u-margin
    Welcome to Postal.
    - if @organizations.size == 1
      You've been invited to join the <b>#{@organizations.first.name}</b> organization. Once accepted, you'll be able to
      access this organization's mail servers.
    - else
      You've been invited to join an organization

  %p.buttonSet
    = link_to "Accept " + (@organizations.size == 1 ? "Invitation" : "Invitations"), '', :class => "button button--positive", :remote => true, :method => :post
    = link_to "Reject " + (@organizations.size == 1 ? "Invitation" : "Invitations"), '', :class => "button button--danger", :remote => true, :method => :delete

app/views/user/new.html.haml
- @wide = true
- page_title << "Signup"
.subPageBox__title
  Join the #{@user_invite.organizations.first.name} organization
= display_flash

.subPageBox__content
  %p.subPageBox__text
    If you don't already have an account on this system, you can create one below. Otherwise, you should
    #{link_to "login to your existing account", login_path(:return_to => join_path(@user_invite.uuid)), :class => 'u-link'}
    and add this organization to that.

  .signupForm
    = form_for @user, :url => signup_path do |f|
      = hidden_field_tag 'return_to', params[:return_to]
      = hidden_field_tag 'invite_token', params[:invite_token]
      = f.error_messages
      .fieldSet.fieldSet--compact.u-margin
        .fieldSet__fieldPair
          .fieldSet__field
            = f.label :first_name, :class => 'fieldSet__label'
            .fieldSet__input= f.text_field :first_name, :class => 'input input--text input--onWhite', :autofocus => true
          .fieldSet__field
            = f.label :last_name, :class => 'fieldSet__label'
            .fieldSet__input= f.text_field :last_name, :class => 'input input--text input--onWhite'
        .fieldSet__field
          = f.label :email_address, :class => 'fieldSet__label'
          .fieldSet__input= f.text_field :email_address, :class => 'input input--text input--onWhite'
        .fieldSet__fieldPair
          .fieldSet__field
            = f.label :password, :class => 'fieldSet__label'
            .fieldSet__input= f.password_field :password, :class => 'input input--text input--onWhite', :placeholder => '•••••••••••'
          .fieldSet__field
            = f.label :password_confirmation, "&nbsp;".html_safe, :class => 'fieldSet__label'
            .fieldSet__input= f.password_field :password_confirmation, :class => 'input input--text input--onWhite', :placeholder => '•••••••••••'

      .loginForm__submit
        %ul.loginForm__links
          %li= link_to "Back to login", login_path(:return_to => params[:return_to])
        %p= submit_tag "Create Account", :class => 'button button--positive', :tabindex => 3

app/views/user/verify.html.haml
- page_title << "Verify your e-mail address"
.pageHeader
  %h1.pageHeader__title
    Please verify your e-mail address
.pageContent.pageContent--compact
  %h2.pageContent__intro.u-margin
    We need to verify that you're the owner of the e-mail address on your account. It is currently <b>#{current_user.email_address}</b>. To
    do this, we've sent you an e-mail with a 6-digit code. Please check your e-mail and enter the code within in the box below.
  %p.pageContent__text
    If you need to change your e-mail address, you can do this in from your #{link_to 'settings page', settings_path, :class => "u-link"}.
    If you haven't received the e-mail, you can #{link_to 'click here to resend it', '', :class => "u-link"}.
  = form_tag request.fullpath, :remote => true do
    = hidden_field_tag 'return_to', params[:return_to]
    %p.u-margin
      = text_field_tag "code", params[:code], :autofocus => true, :class => 'input input--text js-multibox'
    .buttonSet.u-center
      = submit_tag "Verify my e-mail address", :class => 'button button--positive js-form-submit'